name: test
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
      - name: Check Chrome
        run: |
          echo "${{ steps.setup-chrome.outputs.chrome-path }}"
          echo "${{ steps.setup-chrome.outputs.chrome-version }}"
      - name: Lint
        run: deno lint
      - name: Tests
        run: deno task test
      - name: Archive test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sample.test.jpg
          path: test/sample.test.jpg
          retention-days: 3