name: update
on:
  workflow_dispatch:
  schedule:
      - cron: '7 7 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Update dependencies
        run: deno task update
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: auto-update dependencies

